apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: tanzu-java-web-app-3
  labels:
    tanzu.app.live.view: "true"
    tanzu.app.live.view.application.actuator.port: "7777"
    tanzu.app.live.view.application.flavours: spring-boot
    tanzu.app.live.view.application.name: tanzu-java-web-app-3
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/has-tests: "true"
    app.kubernetes.io/part-of: tanzu-java-web-app-3
spec:
  params:
  # - name: gitops_server_address
  #   value: https://github.com/
  # - name: gitops_repository_owner
  #   value: "bagreda-vmw" #github username
  # - name: gitops_repository_name
  #   value: tap-gitops #github repo to push delivery.yml files
  - name: JAVA_TOOL_OPTIONS
    value: >-
      -Dmanagement.server.port=7777
      -Dmanagement.endpoints.web.exposure.include=*
      -Dmanagement.endpoint.health.show-details=always
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  source:
    git:
      url: https://github.com/bagreda-vmw/tanzu-java-web-app-3
      ref:
        branch: main
